DROP TABLE IF EXISTS public.mock_data_import;
DROP TABLE IF EXISTS public.mock_data;

CREATE TABLE public.mock_data (
    id INTEGER PRIMARY KEY,
    customer_first_name VARCHAR(100),
    customer_last_name VARCHAR(100),
    customer_age INTEGER,
    customer_email VARCHAR(200),
    customer_country VARCHAR(100),
    customer_postal_code VARCHAR(20),
    customer_pet_type VARCHAR(50),
    customer_pet_name VARCHAR(100),
    customer_pet_breed VARCHAR(100),
    seller_first_name VARCHAR(100),
    seller_last_name VARCHAR(100),
    seller_email VARCHAR(200),
    seller_country VARCHAR(100),
    seller_postal_code VARCHAR(20),
    product_name VARCHAR(200),
    product_category VARCHAR(100),
    product_price NUMERIC(10,2),
    product_quantity INTEGER,
    sale_date VARCHAR(20),
    sale_customer_id INTEGER,
    sale_seller_id INTEGER,
    sale_product_id INTEGER,
    sale_quantity INTEGER,
    sale_total_price NUMERIC(10,2),
    store_name VARCHAR(200),
    store_location VARCHAR(200),
    store_city VARCHAR(100),
    store_state VARCHAR(100),
    store_country VARCHAR(100),
    store_phone VARCHAR(30),
    store_email VARCHAR(200),
    pet_category VARCHAR(50),
    product_weight NUMERIC(10,2),
    product_color VARCHAR(50),
    product_size VARCHAR(50),
    product_brand VARCHAR(100),
    product_material VARCHAR(100),
    product_description TEXT,
    product_rating NUMERIC(3,1),
    product_reviews INTEGER,
    product_release_date VARCHAR(20),
    product_expiry_date VARCHAR(20),
    supplier_name VARCHAR(200),
    supplier_contact VARCHAR(200),
    supplier_email VARCHAR(200),
    supplier_phone VARCHAR(30),
    supplier_address TEXT,
    supplier_city VARCHAR(100),
    supplier_country VARCHAR(100)
);

CREATE TABLE public.mock_data_import (
    id INTEGER,
    customer_first_name VARCHAR(100),
    customer_last_name VARCHAR(100),
    customer_age INTEGER,
    customer_email VARCHAR(200),
    customer_country VARCHAR(100),
    customer_postal_code VARCHAR(20),
    customer_pet_type VARCHAR(50),
    customer_pet_name VARCHAR(100),
    customer_pet_breed VARCHAR(100),
    seller_first_name VARCHAR(100),
    seller_last_name VARCHAR(100),
    seller_email VARCHAR(200),
    seller_country VARCHAR(100),
    seller_postal_code VARCHAR(20),
    product_name VARCHAR(200),
    product_category VARCHAR(100),
    product_price NUMERIC(10,2),
    product_quantity INTEGER,
    sale_date VARCHAR(20),
    sale_customer_id INTEGER,
    sale_seller_id INTEGER,
    sale_product_id INTEGER,
    sale_quantity INTEGER,
    sale_total_price NUMERIC(10,2),
    store_name VARCHAR(200),
    store_location VARCHAR(200),
    store_city VARCHAR(100),
    store_state VARCHAR(100),
    store_country VARCHAR(100),
    store_phone VARCHAR(30),
    store_email VARCHAR(200),
    pet_category VARCHAR(50),
    product_weight NUMERIC(10,2),
    product_color VARCHAR(50),
    product_size VARCHAR(50),
    product_brand VARCHAR(100),
    product_material VARCHAR(100),
    product_description TEXT,
    product_rating NUMERIC(3,1),
    product_reviews INTEGER,
    product_release_date VARCHAR(20),
    product_expiry_date VARCHAR(20),
    supplier_name VARCHAR(200),
    supplier_contact VARCHAR(200),
    supplier_email VARCHAR(200),
    supplier_phone VARCHAR(30),
    supplier_address TEXT,
    supplier_city VARCHAR(100),
    supplier_country VARCHAR(100)
);

TRUNCATE TABLE public.mock_data_import;
COPY public.mock_data_import FROM '/data/csv/MOCK_DATA.csv' CSV HEADER;
INSERT INTO public.mock_data
SELECT
    id,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    sale_customer_id,
    sale_seller_id,
    sale_product_id,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM public.mock_data_import;

TRUNCATE TABLE public.mock_data_import;
COPY public.mock_data_import FROM '/data/csv/MOCK_DATA (1).csv' CSV HEADER;
INSERT INTO public.mock_data
SELECT
    id + 1000,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    CASE WHEN sale_customer_id IS NULL THEN NULL ELSE sale_customer_id + 1000 END,
    CASE WHEN sale_seller_id IS NULL THEN NULL ELSE sale_seller_id + 1000 END,
    CASE WHEN sale_product_id IS NULL THEN NULL ELSE sale_product_id + 1000 END,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM public.mock_data_import;

TRUNCATE TABLE public.mock_data_import;
COPY public.mock_data_import FROM '/data/csv/MOCK_DATA (2).csv' CSV HEADER;
INSERT INTO public.mock_data
SELECT
    id + 2000,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    CASE WHEN sale_customer_id IS NULL THEN NULL ELSE sale_customer_id + 2000 END,
    CASE WHEN sale_seller_id IS NULL THEN NULL ELSE sale_seller_id + 2000 END,
    CASE WHEN sale_product_id IS NULL THEN NULL ELSE sale_product_id + 2000 END,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM public.mock_data_import;

TRUNCATE TABLE public.mock_data_import;
COPY public.mock_data_import FROM '/data/csv/MOCK_DATA (3).csv' CSV HEADER;
INSERT INTO public.mock_data
SELECT
    id + 3000,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    CASE WHEN sale_customer_id IS NULL THEN NULL ELSE sale_customer_id + 3000 END,
    CASE WHEN sale_seller_id IS NULL THEN NULL ELSE sale_seller_id + 3000 END,
    CASE WHEN sale_product_id IS NULL THEN NULL ELSE sale_product_id + 3000 END,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM public.mock_data_import;

TRUNCATE TABLE public.mock_data_import;
COPY public.mock_data_import FROM '/data/csv/MOCK_DATA (4).csv' CSV HEADER;
INSERT INTO public.mock_data
SELECT
    id + 4000,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    CASE WHEN sale_customer_id IS NULL THEN NULL ELSE sale_customer_id + 4000 END,
    CASE WHEN sale_seller_id IS NULL THEN NULL ELSE sale_seller_id + 4000 END,
    CASE WHEN sale_product_id IS NULL THEN NULL ELSE sale_product_id + 4000 END,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM public.mock_data_import;

TRUNCATE TABLE public.mock_data_import;
COPY public.mock_data_import FROM '/data/csv/MOCK_DATA (5).csv' CSV HEADER;
INSERT INTO public.mock_data
SELECT
    id + 5000,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    CASE WHEN sale_customer_id IS NULL THEN NULL ELSE sale_customer_id + 5000 END,
    CASE WHEN sale_seller_id IS NULL THEN NULL ELSE sale_seller_id + 5000 END,
    CASE WHEN sale_product_id IS NULL THEN NULL ELSE sale_product_id + 5000 END,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM public.mock_data_import;

TRUNCATE TABLE public.mock_data_import;
COPY public.mock_data_import FROM '/data/csv/MOCK_DATA (6).csv' CSV HEADER;
INSERT INTO public.mock_data
SELECT
    id + 6000,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    CASE WHEN sale_customer_id IS NULL THEN NULL ELSE sale_customer_id + 6000 END,
    CASE WHEN sale_seller_id IS NULL THEN NULL ELSE sale_seller_id + 6000 END,
    CASE WHEN sale_product_id IS NULL THEN NULL ELSE sale_product_id + 6000 END,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM public.mock_data_import;

TRUNCATE TABLE public.mock_data_import;
COPY public.mock_data_import FROM '/data/csv/MOCK_DATA (7).csv' CSV HEADER;
INSERT INTO public.mock_data
SELECT
    id + 7000,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    CASE WHEN sale_customer_id IS NULL THEN NULL ELSE sale_customer_id + 7000 END,
    CASE WHEN sale_seller_id IS NULL THEN NULL ELSE sale_seller_id + 7000 END,
    CASE WHEN sale_product_id IS NULL THEN NULL ELSE sale_product_id + 7000 END,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM public.mock_data_import;

TRUNCATE TABLE public.mock_data_import;
COPY public.mock_data_import FROM '/data/csv/MOCK_DATA (8).csv' CSV HEADER;
INSERT INTO public.mock_data
SELECT
    id + 8000,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    CASE WHEN sale_customer_id IS NULL THEN NULL ELSE sale_customer_id + 8000 END,
    CASE WHEN sale_seller_id IS NULL THEN NULL ELSE sale_seller_id + 8000 END,
    CASE WHEN sale_product_id IS NULL THEN NULL ELSE sale_product_id + 8000 END,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM public.mock_data_import;

TRUNCATE TABLE public.mock_data_import;
COPY public.mock_data_import FROM '/data/csv/MOCK_DATA (9).csv' CSV HEADER;
INSERT INTO public.mock_data
SELECT
    id + 9000,
    customer_first_name,
    customer_last_name,
    customer_age,
    customer_email,
    customer_country,
    customer_postal_code,
    customer_pet_type,
    customer_pet_name,
    customer_pet_breed,
    seller_first_name,
    seller_last_name,
    seller_email,
    seller_country,
    seller_postal_code,
    product_name,
    product_category,
    product_price,
    product_quantity,
    sale_date,
    CASE WHEN sale_customer_id IS NULL THEN NULL ELSE sale_customer_id + 9000 END,
    CASE WHEN sale_seller_id IS NULL THEN NULL ELSE sale_seller_id + 9000 END,
    CASE WHEN sale_product_id IS NULL THEN NULL ELSE sale_product_id + 9000 END,
    sale_quantity,
    sale_total_price,
    store_name,
    store_location,
    store_city,
    store_state,
    store_country,
    store_phone,
    store_email,
    pet_category,
    product_weight,
    product_color,
    product_size,
    product_brand,
    product_material,
    product_description,
    product_rating,
    product_reviews,
    product_release_date,
    product_expiry_date,
    supplier_name,
    supplier_contact,
    supplier_email,
    supplier_phone,
    supplier_address,
    supplier_city,
    supplier_country
FROM public.mock_data_import;

DROP TABLE IF EXISTS public.mock_data_import;

CREATE SCHEMA IF NOT EXISTS dwh;

DROP TABLE IF EXISTS dwh.fact_sales;
DROP TABLE IF EXISTS dwh.dim_product;
DROP TABLE IF EXISTS dwh.dim_supplier;
DROP TABLE IF EXISTS dwh.dim_store;
DROP TABLE IF EXISTS dwh.dim_store_location;
DROP TABLE IF EXISTS dwh.dim_category;
DROP TABLE IF EXISTS dwh.dim_seller;
DROP TABLE IF EXISTS dwh.dim_pet;
DROP TABLE IF EXISTS dwh.dim_customer;
DROP TABLE IF EXISTS dwh.dim_date;

CREATE TABLE dwh.dim_customer (
    customer_id INTEGER PRIMARY KEY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    age INTEGER,
    email VARCHAR(200),
    country VARCHAR(100),
    postal_code VARCHAR(20)
);

CREATE TABLE dwh.dim_pet (
    pet_id BIGINT PRIMARY KEY,
    pet_type VARCHAR(50),
    pet_name VARCHAR(100),
    pet_breed VARCHAR(100)
);

CREATE TABLE dwh.dim_seller (
    seller_id INTEGER PRIMARY KEY,
    first_name VARCHAR(100),
    last_name VARCHAR(100),
    email VARCHAR(200),
    country VARCHAR(100),
    postal_code VARCHAR(20)
);

CREATE TABLE dwh.dim_category (
    category_id BIGINT PRIMARY KEY,
    category_name VARCHAR(100)
);

CREATE TABLE dwh.dim_store_location (
    location_id BIGINT PRIMARY KEY,
    location VARCHAR(200),
    city VARCHAR(100),
    state VARCHAR(100),
    country VARCHAR(100)
);

CREATE TABLE dwh.dim_store (
    store_id BIGINT PRIMARY KEY,
    name VARCHAR(200),
    location_id BIGINT REFERENCES dwh.dim_store_location(location_id),
    phone VARCHAR(30),
    email VARCHAR(200)
);

CREATE TABLE dwh.dim_supplier (
    supplier_id BIGINT PRIMARY KEY,
    name VARCHAR(200),
    contact VARCHAR(200),
    email VARCHAR(200),
    phone VARCHAR(30),
    address TEXT,
    city VARCHAR(100),
    country VARCHAR(100)
);

CREATE TABLE dwh.dim_product (
    product_id INTEGER PRIMARY KEY,
    name VARCHAR(200),
    category_id BIGINT REFERENCES dwh.dim_category(category_id),
    price DOUBLE PRECISION,
    quantity INTEGER,
    pet_category VARCHAR(50),
    weight DOUBLE PRECISION,
    color VARCHAR(50),
    size VARCHAR(50),
    brand VARCHAR(100),
    material VARCHAR(100),
    description TEXT,
    rating DOUBLE PRECISION,
    reviews INTEGER,
    release_date DATE,
    expiry_date DATE,
    supplier_id BIGINT REFERENCES dwh.dim_supplier(supplier_id)
);

CREATE TABLE dwh.dim_date (
    date_id BIGINT PRIMARY KEY,
    date_value DATE,
    year INTEGER,
    month INTEGER,
    day INTEGER
);

CREATE TABLE dwh.fact_sales (
    source_row_id INTEGER PRIMARY KEY,
    date_id BIGINT REFERENCES dwh.dim_date(date_id),
    customer_id INTEGER REFERENCES dwh.dim_customer(customer_id),
    pet_id BIGINT REFERENCES dwh.dim_pet(pet_id),
    seller_id INTEGER REFERENCES dwh.dim_seller(seller_id),
    product_id INTEGER REFERENCES dwh.dim_product(product_id),
    store_id BIGINT REFERENCES dwh.dim_store(store_id),
    supplier_id BIGINT REFERENCES dwh.dim_supplier(supplier_id),
    quantity INTEGER,
    total_price DOUBLE PRECISION,
    unit_price DOUBLE PRECISION
);
